# Generated by Django 5.2 on 2025-04-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='source_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL источника'),
        ),
    ]
