# Generated by Django 5.2 on 2025-04-08 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_player_avatar_player_city_player_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL изображения')),
                ('source_url', models.URLField(verbose_name='URL источника')),
                ('published_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Главная новость')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_date'],
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tournament_images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_tournaments', to='tournaments.team', verbose_name='Победитель'),
        ),
    ]
