# Generated by Django 5.2 on 2025-04-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_news_tournament_image_tournament_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='HLTVNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (RU)')),
                ('content', models.TextField(blank=True, verbose_name='Содержание')),
                ('content_ru', models.TextField(blank=True, verbose_name='Содержание (RU)')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL изображения')),
                ('source_url', models.URLField(verbose_name='URL источника')),
                ('published_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('time_ago', models.CharField(blank=True, max_length=50, verbose_name='Время публикации')),
                ('comments_count', models.IntegerField(default=0, verbose_name='Количество комментариев')),
                ('country_code', models.CharField(blank=True, max_length=10, verbose_name='Код страны')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Главная новость')),
            ],
            options={
                'verbose_name': 'Новость HLTV',
                'verbose_name_plural': 'Новости HLTV',
                'ordering': ['-published_date'],
            },
        ),
    ]
