# Generated by Django 5.2 on 2025-04-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_delete_hltvnews_alter_news_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='country',
            field=models.CharField(blank=True, choices=[('', 'Select Country'), ('US', 'United States'), ('UK', 'United Kingdom'), ('RU', 'Russia'), ('UA', 'Ukraine'), ('DE', 'Germany'), ('FR', 'France'), ('BR', 'Brazil'), ('SE', 'Sweden'), ('DK', 'Denmark'), ('FI', 'Finland'), ('NO', 'Norway'), ('CN', 'China'), ('KZ', 'Kazakhstan'), ('EU', 'Europe'), ('MN', 'Mongolia')], max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='country',
            field=models.CharField(blank=True, choices=[('', 'Select Country'), ('US', 'United States'), ('UK', 'United Kingdom'), ('RU', 'Russia'), ('UA', 'Ukraine'), ('DE', 'Germany'), ('FR', 'France'), ('BR', 'Brazil'), ('SE', 'Sweden'), ('DK', 'Denmark'), ('FI', 'Finland'), ('NO', 'Norway'), ('CN', 'China'), ('KZ', 'Kazakhstan'), ('EU', 'Europe'), ('MN', 'Mongolia')], max_length=100),
        ),
    ]
