# Generated by Django 5.2 on 2025-05-02 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_news_source_url'),
        ('tournaments', '0009_alter_match_options_match_match_number_and_more'),
    ]

    operations = [
    ]
